import {
  Activity,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  Award,
  Backpack,
  BadgeCheck,
  Ban,
  Banknote,
  BarChart3,
  Bell,
  BellRing,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarOff,
  CalendarRange,
  CalendarSync,
  Camera,
  Car,
  ChartColumn,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Church,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleDot,
  CircleMinus,
  CirclePlus,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CloudCheck,
  CloudUpload,
  CornerDownRight,
  Cross,
  Database,
  Download,
  Eye,
  EyeOff,
  File,
  FileCheck,
  FilePen,
  FilePlus,
  FileText,
  FileUp,
  Fingerprint,
  FolderArchive,
  FolderCog,
  FolderOpen,
  FolderX,
  Gavel,
  Globe,
  GraduationCap,
  HandHeart,
  Handshake,
  HardHat,
  Headset,
  Heart,
  HeartHandshake,
  HeartPulse,
  History,
  Home,
  Hospital,
  Hourglass,
  House,
  IdCard,
  Image,
  Info,
  Landmark,
  LayoutDashboard,
  LifeBuoy,
  LineChart,
  ListChecks,
  ListFilter,
  ListTodo,
  LoaderCircle,
  Lock,
  LockOpen,
  LogOut,
  Mail,
  MailCheck,
  MapPin,
  Medal,
  Megaphone,
  Menu,
  MessageSquare,
  MessageSquareDot,
  MessagesSquare,
  Network,
  Package,
  PanelLeft,
  Paperclip,
  PartyPopper,
  PenLine,
  Pencil,
  PersonStanding,
  Phone,
  PieChart,
  PiggyBank,
  Plus,
  Printer,
  RefreshCw,
  Reply,
  Route,
  Scale,
  ScanLine,
  ScrollText,
  Search,
  Send,
  Server,
  Shield,
  ShieldCheck,
  ShieldPlus,
  ShieldUser,
  Siren,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  SquarePen,
  Stethoscope,
  SwitchCamera,
  Table,
  Target,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Umbrella,
  Undo2,
  Upload,
  User,
  UserCheck,
  UserCog,
  UserPlus,
  Users,
  Wallet,
  Waypoints,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Ancien nom Material Symbols → tracé simple. Les noms viennent aussi de l'API. */
const ICONES: Record<string, LucideIcon> = {
  account_balance: Landmark,
  account_balance_wallet: Wallet,
  account_tree: Network,
  add: Plus,
  add_a_photo: Camera,
  add_circle: CirclePlus,
  add_moderator: ShieldPlus,
  admin_panel_settings: Shield,
  analytics: LineChart,
  apartment: Building,
  approval_delegation: Route,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  assignment: ClipboardList,
  assignment_ind: ClipboardList,
  assignment_turned_in: ClipboardCheck,
  assured_workload: Landmark,
  attach_file: Paperclip,
  attachment: Paperclip,
  auto_fix_high: Sparkles,
  backpack: Backpack,
  badge: IdCard,
  balance: Scale,
  bar_chart: BarChart3,
  beach_access: Umbrella,
  block: Ban,
  bolt: Zap,
  build: Wrench,
  calculate: Calculator,
  calendar_today: Calendar,
  call: Phone,
  cameraswitch: SwitchCamera,
  campaign: Megaphone,
  cancel: Ban,
  celebration: PartyPopper,
  chat: MessageSquare,
  chat_bubble: MessageSquare,
  check: Check,
  check_circle: CircleCheck,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  church: Church,
  close: X,
  cloud_done: CloudCheck,
  cloud_sync: RefreshCw,
  cloud_upload: CloudUpload,
  construction: HardHat,
  contact_support: LifeBuoy,
  corporate_fare: Building2,
  crisis_alert: Siren,
  dashboard: LayoutDashboard,
  database: Database,
  date_range: CalendarRange,
  deceased: Cross,
  delete: Trash2,
  description: FileText,
  directions_car: Car,
  diversity_1: Users,
  dns: Server,
  document_scanner: ScanLine,
  domain: Building2,
  domain_add: Building2,
  done: Check,
  done_all: CheckCheck,
  download: Download,
  download_done: FileCheck,
  download_for_offline: Download,
  draw: PenLine,
  edit: Pencil,
  edit_calendar: CalendarClock,
  edit_document: FilePen,
  edit_note: FilePen,
  edit_square: SquarePen,
  elderly: PersonStanding,
  emergency: Siren,
  emergency_home: House,
  error: CircleAlert,
  event: Calendar,
  event_available: CalendarCheck,
  event_busy: CalendarOff,
  event_repeat: CalendarSync,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  fact_check: ClipboardCheck,
  family_restroom: Users,
  favorite: Heart,
  file_open: File,
  filter_alt: SlidersHorizontal,
  filter_list: ListFilter,
  fingerprint: Fingerprint,
  folder_managed: FolderCog,
  folder_off: FolderX,
  folder_open: FolderOpen,
  folder_zip: FolderArchive,
  forum: MessagesSquare,
  gavel: Gavel,
  group_add: UserPlus,
  group_work: Users,
  groups: Users,
  handshake: Handshake,
  headset_mic: Headset,
  health_and_safety: HeartPulse,
  help: Info,
  history: History,
  history_edu: GraduationCap,
  history_toggle_off: History,
  home: Home,
  home_work: Building,
  hourglass_empty: Hourglass,
  hourglass_top: Hourglass,
  how_to_reg: UserCheck,
  hub: Waypoints,
  image: Image,
  info: Info,
  ink_pen: PenLine,
  inventory_2: Package,
  local_hospital: Hospital,
  lock: Lock,
  lock_clock: Lock,
  lock_open: LockOpen,
  logout: LogOut,
  mail: Mail,
  manage_accounts: UserCog,
  mark_chat_unread: MessageSquareDot,
  mark_email_read: MailCheck,
  medical_information: HeartPulse,
  medical_services: Stethoscope,
  menu: Menu,
  menu_book: BookOpen,
  menu_open: PanelLeft,
  military_tech: Medal,
  monitoring: Activity,
  move_up: ArrowUp,
  museum: Landmark,
  note_add: FilePlus,
  notification_important: BellRing,
  notifications: Bell,
  notifications_active: BellRing,
  payments: Banknote,
  pending: CircleDashed,
  pending_actions: ListTodo,
  person: User,
  person_add: UserPlus,
  person_check: UserCheck,
  phone: Phone,
  phonelink_lock: Smartphone,
  photo_camera: Camera,
  picture_as_pdf: FileText,
  pie_chart: PieChart,
  pin_drop: MapPin,
  policy: ScrollText,
  poll: ChartColumn,
  post_add: FilePlus,
  print: Printer,
  progress_activity: LoaderCircle,
  public: Globe,
  query_stats: LineChart,
  radio_button_checked: CircleDot,
  radio_button_unchecked: Circle,
  rate_review: MessageSquare,
  real_estate_agent: House,
  refresh: RefreshCw,
  remove_circle: CircleMinus,
  reply: Reply,
  rule: ListChecks,
  savings: PiggyBank,
  schedule: Clock,
  schedule_send: Send,
  school: GraduationCap,
  search: Search,
  security: Shield,
  send: Send,
  shield: Shield,
  shield_locked: ShieldCheck,
  shield_person: ShieldUser,
  shield_with_heart: HeartHandshake,
  subdirectory_arrow_right: CornerDownRight,
  supervisor_account: Users,
  support_agent: Headset,
  swap_horiz: ArrowLeftRight,
  sync: RefreshCw,
  sync_alt: ArrowLeftRight,
  table: Table,
  target: Target,
  task: ListChecks,
  task_alt: CircleCheck,
  timer: Timer,
  trending_down: TrendingDown,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  undo: Undo2,
  upload: Upload,
  upload_file: FileUp,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  visibility: Eye,
  visibility_off: EyeOff,
  volunteer_activism: HandHeart,
  vpn_lock: Shield,
  warning: TriangleAlert,
  work: Briefcase,
  workspace_premium: Award,
};

/** Icône au trait, de la taille du texte qui l'entoure. */
export function Icone({ nom, className, id }: { nom: string; className?: string; id?: string }) {
  const Marque = ICONES[nom] ?? Circle;
  const classes = ["icone inline-block size-[1em] shrink-0 align-middle", className].filter(Boolean).join(" ");
  return <Marque id={id} className={classes} strokeWidth={1.75} aria-hidden />;
}
