# Generated by Django 5.2.17 on 2026-10-02 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=32, unique=True)),
                ('nom', models.CharField(max_length=80)),
                ('prenoms', models.CharField(max_length=120)),
                ('initiales', models.CharField(max_length=4)),
                ('corps', models.CharField(max_length=180)),
                ('grade', models.CharField(max_length=40)),
                ('echelon', models.CharField(max_length=20)),
                ('indice', models.PositiveIntegerField(default=0)),
                ('structure', models.CharField(max_length=240)),
                ('situation', models.CharField(default='En activité', max_length=80)),
                ('anciennete', models.CharField(blank=True, max_length=80)),
                ('prise_service', models.CharField(blank=True, max_length=40)),
                ('visite_medicale', models.CharField(blank=True, max_length=160)),
                ('affiliation_cgrae', models.CharField(blank=True, max_length=160)),
                ('conges_acquis', models.PositiveSmallIntegerField(default=30)),
                ('conges_consommes', models.PositiveSmallIntegerField(default=0)),
                ('categorie', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['nom', 'prenoms'],
            },
        ),
        migrations.CreateModel(
            name='EtapeCircuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(unique=True)),
                ('titre', models.CharField(max_length=80)),
                ('compteur', models.CharField(max_length=16)),
                ('detail', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Organisme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('nom', models.CharField(max_length=220)),
                ('sigle', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name': 'organisme',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ParcoursEtape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(unique=True)),
                ('acteur', models.CharField(max_length=80)),
                ('titre', models.CharField(max_length=120)),
                ('texte', models.TextField()),
                ('metas', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='RoleMatrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(unique=True)),
                ('role', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=180)),
                ('icone', models.CharField(max_length=40)),
                ('droits', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotExercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(unique=True)),
                ('accueil', models.JSONField(default=dict)),
                ('dashboard', models.JSONField(default=dict)),
                ('carriere', models.JSONField(default=dict)),
                ('modules', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Acte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80)),
                ('nature', models.CharField(max_length=120)),
                ('titre', models.CharField(max_length=240)),
                ('resume', models.TextField(blank=True)),
                ('domaine', models.CharField(choices=[('carriere', 'Carrière'), ('social', 'Action sociale'), ('formation', 'Formation'), ('conge', 'Congé')], max_length=20)),
                ('statut', models.CharField(choices=[('valide', 'Validé'), ('instruction', 'Instruction'), ('complement', 'Complément requis'), ('rejete', 'Rejeté')], max_length=20)),
                ('date_effet', models.DateField(blank=True, null=True)),
                ('date_enregistrement', models.DateField()),
                ('signataire', models.CharField(blank=True, max_length=180)),
                ('publie', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actes', to='personnel.agent')),
            ],
            options={
                'ordering': ['-date_enregistrement', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('nature', models.CharField(max_length=140)),
                ('icone', models.CharField(default='edit_note', max_length=40)),
                ('etape', models.CharField(max_length=140)),
                ('responsable', models.CharField(max_length=140)),
                ('echeance', models.CharField(max_length=80)),
                ('depose_le', models.DateField()),
                ('categorie', models.CharField(max_length=40)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='personnel.agent')),
            ],
            options={
                'ordering': ['-depose_le'],
            },
        ),
        migrations.CreateModel(
            name='LigneAvancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emploi', models.CharField(max_length=180)),
                ('structure', models.CharField(max_length=200)),
                ('grade_echelon', models.CharField(max_length=80)),
                ('anciennete', models.CharField(max_length=80)),
                ('proposition', models.CharField(max_length=80)),
                ('mode', models.CharField(max_length=80)),
                ('note', models.CharField(max_length=16)),
                ('avis', models.CharField(max_length=80)),
                ('statut', models.CharField(max_length=80)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avancements', to='personnel.agent')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='organisme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='personnel.organisme'),
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(max_length=160)),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profils', to='personnel.organisme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisaEnAttente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=280)),
                ('echeance', models.CharField(max_length=120)),
                ('visa_amont', models.CharField(max_length=180)),
                ('categorie', models.CharField(max_length=40)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visas', to='personnel.agent')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
