# Generated by Django 5.2.17 on 2026-10-03 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='courriel',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='agent',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='habilitation',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='agent',
            name='localisation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='agent',
            name='sexe',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='agent',
            name='telephone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='visaenattente',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=120)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('jours', models.PositiveSmallIntegerField()),
                ('statut', models.CharField(max_length=40)),
                ('interim', models.CharField(blank=True, max_length=160)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='personnel.agent')),
            ],
            options={
                'ordering': ['-debut'],
            },
        ),
        migrations.CreateModel(
            name='AlerteReleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=180)),
                ('depart', models.DateField()),
                ('vivier', models.PositiveSmallIntegerField(help_text='Candidats internes éligibles')),
                ('vivier_cible', models.PositiveSmallIntegerField(default=3)),
                ('risque', models.CharField(choices=[('eleve', 'Élevé'), ('modere', 'Modéré'), ('faible', 'Faible')], max_length=20)),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertes', to='personnel.organisme')),
                ('titulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='personnel.agent')),
            ],
            options={
                'ordering': ['depart'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField()),
                ('note', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mention', models.CharField(max_length=40)),
                ('appreciation', models.TextField()),
                ('evaluateur', models.CharField(max_length=120)),
                ('fonction_evaluateur', models.CharField(max_length=160)),
                ('statut', models.CharField(default='Notifiée', max_length=40)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='personnel.agent')),
            ],
            options={
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('organisme', models.CharField(max_length=160)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('heures', models.PositiveSmallIntegerField()),
                ('statut', models.CharField(max_length=40)),
                ('certification', models.CharField(blank=True, max_length=160)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='personnel.agent')),
            ],
            options={
                'ordering': ['-debut'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStrategique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=180)),
                ('nature', models.CharField(max_length=80)),
                ('statut', models.CharField(max_length=80)),
                ('date_effet', models.DateField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='personnel.agent')),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='personnel.organisme')),
            ],
            options={
                'ordering': ['date_effet'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('categorie', models.CharField(max_length=80)),
                ('date_depot', models.DateField()),
                ('taille_ko', models.PositiveIntegerField()),
                ('verifiee', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='personnel.agent')),
            ],
            options={
                'ordering': ['categorie', '-date_depot'],
            },
        ),
        migrations.CreateModel(
            name='PrestationSociale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40)),
                ('nature', models.CharField(max_length=120)),
                ('objet', models.CharField(max_length=240)),
                ('montant', models.PositiveIntegerField(help_text='Montant en FCFA')),
                ('date_demande', models.DateField()),
                ('statut', models.CharField(max_length=40)),
                ('echeancier', models.CharField(blank=True, max_length=160)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='personnel.agent')),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='VisaDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField()),
                ('instance', models.CharField(max_length=120)),
                ('titulaire', models.CharField(max_length=120)),
                ('fonction', models.CharField(max_length=160)),
                ('avis', models.CharField(max_length=40)),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visas_dossier', to='personnel.agent')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
