# Generated by Django 5.2.17 on 2026-10-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_dossier_complet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acte',
            name='statut',
            field=models.CharField(choices=[('valide', 'Validé'), ('instruction', 'En instruction'), ('complement', 'Complément requis'), ('rejete', 'Rejeté')], max_length=20),
        ),
    ]
