# Generated by Django 5.2.17 on 2026-10-03 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_libelle_statut_instruction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('visa', 'Visa à apposer'), ('demande', 'Demande en circuit'), ('releve', 'Relève des postes clés'), ('dossier', 'Dossier agent'), ('systeme', 'Système')], max_length=20)),
                ('titre', models.CharField(max_length=160)),
                ('message', models.CharField(max_length=280)),
                ('lien', models.CharField(blank=True, help_text='Route du front ouverte au clic', max_length=200)),
                ('urgente', models.BooleanField(default=False)),
                ('lue', models.BooleanField(default=False)),
                ('creee_le', models.DateTimeField()),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lue', '-creee_le'],
            },
        ),
    ]
