# Generated by Django 5.2.17 on 2026-10-03 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaenattente',
            name='acte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visas_drh', to='personnel.acte'),
        ),
        migrations.AddField(
            model_name='visaenattente',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('vise', 'Visé'), ('complement', 'Complément demandé')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='visaenattente',
            name='traite_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
