# Generated by Django 5.2.17 on 2026-10-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_piece_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='acte',
            name='scan',
            field=models.FileField(blank=True, upload_to='entetes/%Y/%m'),
        ),
        migrations.AddField(
            model_name='profil',
            name='signature',
            field=models.FileField(blank=True, upload_to='signatures/%Y/%m'),
        ),
        migrations.AddField(
            model_name='visaenattente',
            name='signature',
            field=models.FileField(blank=True, upload_to='visas/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='acte',
            name='statut',
            field=models.CharField(choices=[('valide', 'Validé'), ('accorde', 'Accord acquis — papier à en-tête à établir'), ('instruction', 'En instruction'), ('complement', 'Complément requis'), ('rejete', 'Rejeté')], max_length=20),
        ),
    ]
