# Generated by Django 5.2.17 on 2026-10-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0011_visa_demande_signataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='photo',
            field=models.FileField(blank=True, upload_to='portraits/%Y/%m'),
        ),
    ]
