# Generated by Django 5.2.17 on 2026-10-03 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0012_agent_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositifSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('ancre', models.CharField(max_length=80)),
                ('valeur', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AyantDroit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=160)),
                ('lien', models.CharField(max_length=40)),
                ('detail', models.CharField(blank=True, max_length=160)),
                ('statut', models.CharField(max_length=40)),
                ('initiales', models.CharField(max_length=4)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayants_droit', to='personnel.agent')),
            ],
            options={
                'ordering': ['lien', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='SituationSociale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cmu', models.CharField(blank=True, max_length=40)),
                ('traitement_brut', models.PositiveIntegerField(help_text='FCFA')),
                ('cotisations', models.PositiveIntegerField(help_text='FCFA')),
                ('engagements', models.PositiveIntegerField(default=0, help_text='Prélèvements en cours, FCFA')),
                ('taux_quotite', models.DecimalField(decimal_places=2, default=33, max_digits=5)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='situation_sociale', to='personnel.agent')),
            ],
        ),
        migrations.CreateModel(
            name='EnveloppeSociale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercice', models.PositiveSmallIntegerField()),
                ('ligne', models.CharField(max_length=80)),
                ('allouee', models.PositiveIntegerField()),
                ('engagee', models.PositiveIntegerField()),
                ('session_numero', models.PositiveSmallIntegerField(default=1)),
                ('session_date', models.DateField()),
                ('contact', models.CharField(blank=True, max_length=120)),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enveloppes_sociales', to='personnel.organisme')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organisme', 'exercice'), name='enveloppe_sociale_unique')],
            },
        ),
    ]
