# Generated by Django 5.2.17 on 2026-10-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0013_action_sociale'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='autorisations_acquises',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='agent',
            name='report_conges',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organisme',
            name='quorum_presence',
            field=models.PositiveSmallIntegerField(default=65),
        ),
    ]
