# Generated by Django 5.2.17 on 2026-10-03 10:58

import django.db.models.deletion
from django.db import migrations, models


TYPES = [
    ("conge-annuel", "Congé annuel", "", 1),
    ("conge-maternite", "Congé de maternité", "", 2),
    ("conge-paternite", "Congé de paternité", "", 3),
    ("conge-parental", "Congé parental", "", 4),
    ("conge-maladie", "Congé de maladie", "", 5),
    ("maladie-courte", "Congé de maladie de courte durée", "conge-maladie", 6),
    ("maladie-longue", "Congé de maladie de longue durée", "conge-maladie", 7),
]


def charger_types(apps, schema_editor):
    TypeConge = apps.get_model("personnel", "TypeConge")
    for code, libelle, parent, ordre in TYPES:
        TypeConge.objects.update_or_create(
            code=code,
            defaults={"libelle": libelle, "ordre": ordre, "parent": TypeConge.objects.filter(code=parent).first()},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0014_conges_presence'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('libelle', models.CharField(max_length=80)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='personnel.typeconge')),
            ],
            options={
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.RunPython(charger_types, migrations.RunPython.noop),
    ]
