# Generated by Django 5.2.17 on 2026-10-03 11:01

from django.db import migrations, models


TYPES = [
    ("demission", "Démission", 1),
    ("licenciement", "Licenciement", 2),
    ("revocation", "Révocation", 3),
    ("retraite", "Admission à la retraite", 4),
    ("deces", "Décès", 5),
]


def charger_types(apps, schema_editor):
    TypeFinCarriere = apps.get_model("personnel", "TypeFinCarriere")
    for code, libelle, ordre in TYPES:
        TypeFinCarriere.objects.update_or_create(code=code, defaults={"libelle": libelle, "ordre": ordre})


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0015_types_conges'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFinCarriere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('libelle', models.CharField(max_length=80)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.RunPython(charger_types, migrations.RunPython.noop),
    ]
