# Generated by Django 5.2.17 on 2026-10-03 11:04

import django.db.models.deletion
from django.db import migrations, models


TYPES = [
    ("PREP", "Cycles de Préparation aux concours professionnels", 1, [
        "Fonctionnaires candidats",
    ]),
    ("CARR", "Cycles et stage de formation d'accompagnement de carrière", 2, [
        "Fonctionnaires admis aux concours professionnel bénéficiaires",
        "Fonctionnaires nommés à un poste de responsabilité",
    ]),
    ("CATEG", "Cycles et stage de formation catégorielle", 3, [
        "Fonctionnaires admis aux concours professionnel bénéficiaires",
    ]),
    ("PERF", "Cycles, séminaire et stage de perfectionnement", 4, [
        "Fonctionnaires bénéficiaires",
    ]),
    ("SPEC", "Cycles et stage de spécialisation", 5, [
        "Fonctionnaires bénéficiaires",
    ]),
]


def charger_types(apps, schema_editor):
    TypeFormation = apps.get_model("personnel", "TypeFormation")
    PublicFormation = apps.get_model("personnel", "PublicFormation")
    for code, libelle, ordre, publics in TYPES:
        cycle, _ = TypeFormation.objects.update_or_create(code=code, defaults={"libelle": libelle, "ordre": ordre})
        cycle.publics.all().delete()
        for index, public in enumerate(publics, start=1):
            PublicFormation.objects.create(type_formation=cycle, libelle=public, ordre=index)


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0016_types_fin_carriere'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('libelle', models.CharField(max_length=160)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='PublicFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=160)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('type_formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publics', to='personnel.typeformation')),
            ],
            options={
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.RunPython(charger_types, migrations.RunPython.noop),
    ]
