# Generated by Django 5.2.17 on 2026-10-03 11:06

from django.db import migrations, models


TYPES = [
    ("arrete-nomination", "Arrêté de nomination", 1),
    ("certificate-premiere-prise", "Certificate de première prise de service", 2),
    ("cessation", "Cessation", 3),
    ("certificat-prise", "Certificat de prise de service", 4),
    ("acte-nomination-fonction", "Acte de nomination dans une fonction", 5),
    ("cv", "CV", 6),
    ("extrait-naissance", "Extrait de naissance", 7),
    ("cni", "CNI", 8),
]


def charger_types(apps, schema_editor):
    TypeActe = apps.get_model("personnel", "TypeActe")
    for code, libelle, ordre in TYPES:
        TypeActe.objects.update_or_create(code=code, defaults={"libelle": libelle, "ordre": ordre})


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0017_types_formation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeActe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('libelle', models.CharField(max_length=160)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.RunPython(charger_types, migrations.RunPython.noop),
    ]
