# Generated by Django 5.2.17 on 2026-10-03 11:15

import datetime

import django.db.models.deletion
from django.db import migrations, models

OUVERTURE = datetime.date(2026, 1, 12)


def ouvrir_sessions(apps, schema_editor):
    TypeFormation = apps.get_model("personnel", "TypeFormation")
    SessionFormation = apps.get_model("personnel", "SessionFormation")
    for cycle in TypeFormation.objects.all():
        SessionFormation.objects.update_or_create(
            code=cycle.code,
            defaults={"type_formation": cycle, "ouverte": True, "ouverte_le": OUVERTURE},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0018_types_actes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('ouverte', models.BooleanField(default=False)),
                ('ouverte_le', models.DateField(blank=True, null=True)),
                ('type_formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='personnel.typeformation')),
            ],
            options={
                'ordering': ['type_formation__ordre', 'code'],
            },
        ),
        migrations.RunPython(ouvrir_sessions, migrations.RunPython.noop),
    ]
