# Generated by Django 5.2.17 on 2026-10-03 11:25

import datetime

import django.db.models.deletion
from django.db import migrations, models

OUVERTURE = datetime.date(2026, 1, 12)
CADRE = "Dotation FDFP ministérielle, exercice 2026"
MODULES = [
    ("prep-admin", "PREP", "Préparation au concours d'administrateur civil", "Réussite des épreuves du concours professionnel d'administrateur civil"),
    ("prep-redacteur", "PREP", "Préparation au concours de rédacteur", "Maîtrise des épreuves écrites du concours de rédacteur"),
    ("carr-fonction", "CARR", "Accompagnement à la prise de fonction", "Installation dans le poste de responsabilité"),
    ("carr-admis", "CARR", "Stage des admis au concours professionnel", "Intégration dans le corps d'accueil"),
    ("categ-corps", "CATEG", "Formation catégorielle du corps d'accueil", "Acquisition des fondamentaux du nouveau corps"),
    ("perf-pilotage", "PERF", "Séminaire de perfectionnement au pilotage", "Amélioration des pratiques de gestion"),
    ("perf-donnees", "PERF", "Stage de perfectionnement à l'analyse de données", "Lecture et exploitation des tableaux de bord"),
    ("spec-controle", "SPEC", "Stage de spécialisation en contrôle de gestion", "Maîtrise des outils de contrôle"),
]


def charger_modules(apps, schema_editor):
    TypeFormation = apps.get_model("personnel", "TypeFormation")
    SessionFormation = apps.get_model("personnel", "SessionFormation")
    TypeFormation.objects.filter(code="PREP").update(
        piece_requise=True,
        piece_libelle="Document d'inscription au concours",
    )
    SessionFormation.objects.all().delete()
    for code, type_code, libelle, objectif in MODULES:
        cycle = TypeFormation.objects.filter(code=type_code).first()
        if cycle is None:
            continue
        SessionFormation.objects.create(
            code=code,
            type_formation=cycle,
            libelle=libelle,
            cadre_budgetaire=CADRE,
            objectif=objectif,
            ouverte=True,
            ouverte_le=OUVERTURE,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0019_sessions_formation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionformation',
            options={'ordering': ['type_formation__ordre', 'libelle']},
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='cadre_budgetaire',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='libelle',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='objectif',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='typeformation',
            name='piece_libelle',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='typeformation',
            name='piece_requise',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InscriptionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(blank=True, upload_to='inscriptions/%Y/%m')),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inscription_formation', to='personnel.demande')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='personnel.sessionformation')),
            ],
        ),
        migrations.RunPython(charger_modules, migrations.RunPython.noop),
    ]
