# Generated by Django 5.2.17 on 2026-10-03 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0023_circuits_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchePlafond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('libelle', models.CharField(max_length=180)),
                ('entites', models.CharField(max_length=240)),
                ('icone', models.CharField(max_length=40)),
                ('effectif', models.PositiveIntegerField()),
                ('plafond', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='CampagneBesoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercice', models.PositiveSmallIntegerField(unique=True)),
                ('ouverte', models.BooleanField(default=True)),
                ('cadrage', models.CharField(max_length=180)),
                ('pea_max', models.PositiveIntegerField()),
                ('volume_precedent', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-exercice'],
            },
        ),
        migrations.CreateModel(
            name='EntiteTutelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('nom', models.CharField(max_length=220)),
            ],
            options={
                'verbose_name': 'entité sous tutelle',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ExerciceDotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField(unique=True)),
                ('intitule', models.CharField(max_length=180)),
                ('fondement', models.CharField(max_length=180)),
                ('masse_salariale', models.BigIntegerField(default=0)),
                ('ratio_masse', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('seuil_ratio', models.DecimalField(decimal_places=1, default=35, max_digits=4)),
            ],
            options={
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='FiliereBesoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('icone', models.CharField(max_length=40)),
                ('requis', models.PositiveIntegerField()),
                ('couverts', models.PositiveIntegerField()),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='JournalEffectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40)),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=180)),
                ('cree_le', models.DateTimeField()),
            ],
            options={
                'ordering': ['-cree_le', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Passerelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedant', models.CharField(max_length=180)),
                ('recepteur', models.CharField(max_length=180)),
                ('profil', models.CharField(max_length=200)),
                ('effectif', models.PositiveSmallIntegerField()),
                ('economie', models.BigIntegerField(default=0)),
                ('statut', models.CharField(choices=[('proposee', 'Proposée'), ('actee', 'Actée')], default='proposee', max_length=20)),
                ('note', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlanFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField(unique=True)),
                ('dotation', models.PositiveBigIntegerField(default=0, help_text='En FCFA')),
                ('objectif_agents', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=160, unique=True)),
                ('categorie', models.CharField(choices=[('ecole', 'École publique de formation'), ('institut', 'Institut ou université'), ('cabinet', 'Cabinet privé agréé'), ('interne', 'Formateurs internes')], max_length=20)),
                ('specialites', models.CharField(blank=True, max_length=240)),
                ('ville', models.CharField(blank=True, max_length=80)),
                ('contact_nom', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_telephone', models.CharField(blank=True, max_length=40)),
                ('convention_debut', models.DateField(blank=True, null=True)),
                ('convention_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='inscriptionformation',
            name='note_satisfaction',
            field=models.PositiveSmallIntegerField(blank=True, help_text='De 1 à 5', null=True),
        ),
        migrations.AddField(
            model_name='inscriptionformation',
            name='present',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='annulee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='cloturee_le',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='cout_participant',
            field=models.PositiveIntegerField(default=0, help_text='Coût par participant, en FCFA'),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='formateur',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='heures',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='lieu',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='motif_annulation',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='places',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.CreateModel(
            name='BesoinFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField()),
                ('intitule', models.CharField(max_length=200)),
                ('effectif', models.PositiveSmallIntegerField(default=1)),
                ('priorite', models.CharField(choices=[('haute', 'Haute'), ('moyenne', 'Moyenne'), ('basse', 'Basse')], default='moyenne', max_length=10)),
                ('statut', models.CharField(choices=[('exprime', 'Exprimé'), ('retenu', 'Retenu au plan'), ('couvert', 'Couvert par une session')], default='exprime', max_length=10)),
                ('exprime_le', models.DateField()),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='besoins_formation', to='personnel.organisme')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='besoins', to='personnel.sessionformation')),
                ('type_formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='besoins', to='personnel.typeformation')),
            ],
            options={
                'ordering': ['-annee', 'statut', '-exprime_le'],
            },
        ),
        migrations.CreateModel(
            name='DemandeDotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('direction', models.CharField(max_length=180)),
                ('poste', models.CharField(max_length=200)),
                ('nature', models.CharField(choices=[('cadre', 'Recrutement cadre supérieur'), ('concours', 'Concours direct homologué'), ('mobilite', 'Mobilité / mutation interne'), ('derogatoire', 'Recrutement dérogatoire')], max_length=20)),
                ('impact', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('arbitrage', 'En arbitrage DGPE'), ('visa_cf', 'Visa contrôle financier requis'), ('acte', 'Avis favorable / acté'), ('rejet', 'Rejet / plafond atteint')], default='arbitrage', max_length=20)),
                ('visa', models.CharField(blank=True, max_length=180)),
                ('detail', models.CharField(blank=True, max_length=240)),
                ('recu_le', models.DateField()),
                ('notifiee', models.BooleanField(default=False)),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_dotation', to='personnel.entitetutelle')),
            ],
            options={
                'ordering': ['-recu_le', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AlertePoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=280)),
                ('postes', models.PositiveSmallIntegerField()),
                ('jours', models.PositiveSmallIntegerField(default=0)),
                ('piste', models.CharField(max_length=200)),
                ('traitee', models.BooleanField(default=False)),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertes_postes', to='personnel.entitetutelle')),
            ],
            options={
                'ordering': ['-jours', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FicheBesoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('direction', models.CharField(max_length=180)),
                ('profil', models.CharField(max_length=200)),
                ('grade', models.CharField(blank=True, max_length=40)),
                ('specialite', models.CharField(blank=True, max_length=120)),
                ('volume', models.PositiveSmallIntegerField()),
                ('motif', models.CharField(max_length=240)),
                ('nature', models.CharField(choices=[('creation', 'Création nette de poste'), ('remplacement', 'Remplacement départ retraite'), ('mobilite', 'Mobilité inter-entreprises'), ('renfort', 'Renfort stratégique provisoire')], max_length=20)),
                ('statut', models.CharField(choices=[('favorable', 'Arbitré favorable DGPE'), ('instruction', "En attente d'avis technique"), ('complement', 'Renvoyé pour complément'), ('rejet', 'Rejeté (contrainte PEA)')], default='instruction', max_length=20)),
                ('arbitrage', models.CharField(blank=True, max_length=180)),
                ('visa', models.CharField(blank=True, max_length=180)),
                ('detail', models.CharField(blank=True, max_length=240)),
                ('cout_annuel', models.BigIntegerField(default=0)),
                ('critique', models.BooleanField(default=False)),
                ('postes_accordes', models.PositiveSmallIntegerField(default=0)),
                ('depose_le', models.DateTimeField()),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches_besoin', to='personnel.entitetutelle')),
            ],
            options={
                'ordering': ['-depose_le', '-id'],
            },
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='prestataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='personnel.prestataire'),
        ),
    ]
