# Generated by Django 5.2.17 on 2026-10-03 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0037_arbitrage_conges'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionParitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('intitule', models.CharField(max_length=120)),
                ('date', models.DateTimeField()),
                ('etat', models.CharField(choices=[('convoquee', 'Convocation notifiée'), ('a_confirmer', 'En cours de confirmation'), ('tenue', 'Séance tenue')], default='a_confirmer', max_length=20)),
                ('ordre_du_jour', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('composition', models.JSONField(default=list)),
                ('lieu', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureDisciplinaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('saisine', models.DateField()),
                ('grief', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('degre', models.PositiveSmallIntegerField(default=1, help_text='Degré de sanction encouru (1 à 3)')),
                ('rapporteur', models.CharField(max_length=120)),
                ('stade', models.CharField(max_length=120)),
                ('stade_detail', models.CharField(blank=True, max_length=160)),
                ('avis', models.CharField(choices=[('instruction', 'Instruction ouverte'), ('recevable', 'Recevabilité validée'), ('attente_reponse', 'En attente de réponse'), ('visa_rapporteur', 'Visa du rapporteur'), ('delibere', 'En délibéré paritaire'), ('sanction', 'Sanction prononcée'), ('classee', 'Classée sans suite')], default='instruction', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='personnel.agent')),
            ],
            options={
                'ordering': ['saisine', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='SanctionDisciplinaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('avertissement', 'Avertissement'), ('blame', 'Blâme'), ('deplacement', "Déplacement d'office"), ('retrogradation', 'Rétrogradation'), ('exclusion', 'Exclusion temporaire'), ('revocation', 'Révocation')], max_length=20)),
                ('degre', models.PositiveSmallIntegerField(default=1)),
                ('prononcee_le', models.DateField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='personnel.agent')),
            ],
            options={
                'ordering': ['-prononcee_le'],
            },
        ),
    ]
