# Generated by Django 5.2.17 on 2026-10-03 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0039_donnees_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierRetraite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_limite', models.PositiveSmallIntegerField(default=60)),
                ('entree_service', models.DateField(blank=True, null=True)),
                ('idr', models.PositiveIntegerField(default=0, help_text='Indemnité de départ à la retraite, en FCFA')),
                ('pension', models.PositiveIntegerField(default=0, help_text='Pension mensuelle provisoire, en FCFA')),
                ('statut', models.CharField(choices=[('visite', 'Visite médicale de sortie'), ('quittance', 'Quittance de fin de gestion'), ('arrete', 'Arrêté signé'), ('transmis', 'Transmis à la CGRAE'), ('notifie', 'CGRAE notifiée')], default='visite', max_length=20)),
                ('statut_detail', models.CharField(blank=True, max_length=160)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_retraite', to='personnel.agent')),
            ],
            options={
                'ordering': ['agent__date_naissance'],
            },
        ),
        migrations.CreateModel(
            name='PosteSensible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=160)),
                ('depart', models.DateField()),
                ('successeur', models.CharField(blank=True, max_length=160)),
                ('progression', models.PositiveSmallIntegerField(default=0, help_text='Avancement du tutorat, en %')),
                ('commentaire', models.CharField(blank=True, max_length=200)),
                ('titulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes_sensibles', to='personnel.agent')),
            ],
            options={
                'ordering': ['depart'],
            },
        ),
    ]
