# Generated by Django 5.2.17 on 2026-10-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0041_donnees_fin_carriere'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestationsociale',
            name='avis_commission',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='prestationsociale',
            name='ayant_droit',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='prestationsociale',
            name='etat',
            field=models.CharField(blank=True, choices=[('commission', 'Avis de la commission attendu'), ('conforme', 'Conforme pour ordonnancement'), ('reserve', 'Pièces manquantes'), ('mandatee', 'Mandatée')], max_length=20),
        ),
        migrations.AddField(
            model_name='prestationsociale',
            name='pieces',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prestationsociale',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
