# Generated by Django 5.2.17 on 2026-10-04 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0045_donnees_notations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositionStatistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=160)),
                ('sujet', models.SlugField(max_length=40)),
                ('mesure', models.SlugField(max_length=40)),
                ('axe_lignes', models.SlugField(max_length=40)),
                ('axe_colonnes', models.SlugField(blank=True, max_length=40)),
                ('filtres', models.JSONField(default=list)),
                ('creee_le', models.DateTimeField(auto_now_add=True)),
                ('modifiee_le', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions_statistiques', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'composition statistique',
                'verbose_name_plural': 'compositions statistiques',
                'ordering': ['-modifiee_le', '-id'],
            },
        ),
    ]
