# Generated by Django 5.2.17 on 2026-10-04 04:07

import django.db.models.deletion
from django.db import migrations, models


def semer(apps, schema_editor):
    from personnel.nomenclature import charger

    charger(apps.get_model("personnel", "GradeReferentiel"), apps.get_model("personnel", "EmploiReferentiel"))


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0047_composition_volets'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeReferentiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('categorie', models.CharField(max_length=1)),
                ('libelle', models.CharField(max_length=320)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('en_vigueur', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'grade',
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='demandedotation',
            name='statut',
            field=models.CharField(choices=[('arbitrage', 'En arbitrage DGPE'), ('visa_cf', 'Contrôle des emplois'), ('acte', 'Avis favorable / acté'), ('rejet', 'Rejet / plafond atteint')], default='arbitrage', max_length=20),
        ),
        migrations.CreateModel(
            name='EmploiReferentiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=96, unique=True)),
                ('libelle', models.CharField(max_length=220)),
                ('famille', models.CharField(max_length=40)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emplois', to='personnel.gradereferentiel')),
            ],
            options={
                'verbose_name': 'emploi',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.RunPython(semer, migrations.RunPython.noop),
    ]
