# Generated by Django 5.2.17 on 2026-10-04 04:19

from django.db import migrations, models

COLONNES = (
    "Dossier Agent",
    "Carrières & Actes",
    "Social & Santé",
    "Formations",
    "Statistiques & RBAC",
)


def semer(apps, schema_editor):
    Module = apps.get_model("personnel", "ModuleHabilitation")
    if Module.objects.exists():
        return
    for ordre, libelle in enumerate(COLONNES, start=1):
        Module.objects.create(ordre=ordre, libelle=libelle)


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0048_grades_et_emplois'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleHabilitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(unique=True)),
                ('libelle', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': "module d'habilitation",
                'ordering': ['ordre'],
            },
        ),
        migrations.RunPython(semer, migrations.RunPython.noop),
    ]
