# Generated by Django 5.2.17 on 2026-10-04 04:30

import django.db.models.deletion
from django.db import migrations, models

DETAILS = {
    "Dossier Agent": (
        "Consultation du dossier",
        "Identité et coordonnées",
        "Pièces et actes",
    ),
    "Carrières & Actes": (
        "Situation administrative",
        "Absences",
        "Congés",
        "Procédures disciplinaires",
        "Fin de carrière",
    ),
    "Social & Santé": (
        "Demandes d'aide",
        "Prêts et fonds de solidarité",
    ),
    "Formations": (
        "Plan et sessions",
        "Inscriptions",
        "Besoins de formation",
    ),
    "Statistiques & RBAC": (
        "Statistiques",
        "Circuits et habilitations",
        "Comptes utilisateurs",
        "Structures du ministère",
    ),
}


def semer(apps, schema_editor):
    Module = apps.get_model("personnel", "ModuleHabilitation")
    Fonction = apps.get_model("personnel", "FonctionHabilitation")
    if Fonction.objects.exists():
        return
    for libelle_module, fonctions in DETAILS.items():
        module = Module.objects.filter(libelle=libelle_module).first()
        if module is None:
            continue
        for ordre, libelle in enumerate(fonctions, start=1):
            Fonction.objects.create(module=module, ordre=ordre, libelle=libelle)


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0050_habilitations_compte'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolematrice',
            name='precisions',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='FonctionHabilitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField()),
                ('libelle', models.CharField(max_length=80)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonctions', to='personnel.modulehabilitation')),
            ],
            options={
                'verbose_name': "fonction d'habilitation",
                'ordering': ['module__ordre', 'ordre'],
                'constraints': [models.UniqueConstraint(fields=('module', 'ordre'), name='fonction_habilitation_ordre'), models.UniqueConstraint(fields=('module', 'libelle'), name='fonction_habilitation_libelle')],
            },
        ),
        migrations.RunPython(semer, migrations.RunPython.noop),
    ]
