# Generated by Django 5.2.17 on 2026-10-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0051_fonctions_habilitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='precisions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
