# Generated by Django 5.2.17 on 2026-10-04 06:52

import django.db.models.deletion
from datetime import date

from django.conf import settings
from django.db import migrations, models

from personnel.communications import ANNONCES_INITIALES


def semer(apps, schema_editor):
    Communication = apps.get_model("personnel", "Communication")
    if Communication.objects.exists():
        return
    User = apps.get_model("auth", "User")
    auteur = User.objects.filter(username="DRH-2018-044").first()
    for annonce in ANNONCES_INITIALES:
        Communication.objects.create(
            titre=annonce["titre"],
            texte=annonce["texte"],
            rubrique=annonce["rubrique"],
            publie=True,
            publie_le=date.fromisoformat(annonce["publie_le"]),
            auteur=auteur,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0055_communication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('texte', models.TextField()),
                ('rubrique', models.CharField(choices=[('information', 'Information'), ('avis', 'Avis'), ('campagne', 'Campagne'), ('note', 'Note de service')], default='information', max_length=20)),
                ('publie', models.BooleanField(default=False)),
                ('publie_le', models.DateField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'communication',
                'ordering': ['-publie_le', '-modifie_le', '-id'],
            },
        ),
        migrations.RunPython(semer, migrations.RunPython.noop),
    ]
