# Generated by Django 5.2.17 on 2026-10-04 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0057_publication_piece'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponseSondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix', models.CharField(max_length=160)),
                ('repondu_le', models.DateTimeField(auto_now_add=True)),
                ('lecteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_sondages', to=settings.AUTH_USER_MODEL)),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='personnel.consultationflash')),
            ],
            options={
                'verbose_name': 'réponse à un sondage',
                'constraints': [models.UniqueConstraint(fields=('sondage', 'lecteur'), name='reponse_sondage_unique')],
            },
        ),
    ]
