# Generated by Django 5.2.17 on 2026-10-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0082_couleurs_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositionstatistique',
            name='configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Zones du tableau croisé (filtres, colonnes, lignes, valeurs), tri, options et graphique.'),
        ),
        migrations.AlterField(
            model_name='compositionstatistique',
            name='axe_lignes',
            field=models.SlugField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='compositionstatistique',
            name='filtres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='compositionstatistique',
            name='mesure',
            field=models.SlugField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='compositionstatistique',
            name='sujet',
            field=models.SlugField(help_text='Source de données du tableau.', max_length=40),
        ),
        migrations.AlterField(
            model_name='compositionstatistique',
            name='volets',
            field=models.JSONField(blank=True, default=list, help_text='Dossiers réunis dans la même composition.'),
        ),
        migrations.AlterField(
            model_name='entitetutelle',
            name='niveau',
            field=models.CharField(choices=[('ministere', 'Ministère'), ('direction-generale', 'Direction générale'), ('direction-centrale', 'Direction centrale'), ('sous-direction', 'Sous-direction'), ('service', 'Service')], default='direction-centrale', max_length=20),
        ),
    ]
